version: '3.8'

services:

  reactapp:
    build: client/
    volumes:
      - './client/src:/usr/src/app/src'
    ports: 
      - 3001:3000
    restart: unless-stopped
    depends_on: 
      - nodeapp

  nodeapp:
    build: .    
    ports:
      - 5001:5000
    restart: unless-stopped
    
